POST http://localhost:3004/users/
Content-Type: application/json

{
  "username": "rahul",
  "name": "Rahul Attuluri",
  "password": "rahul12",
  "gender": "male",
  "location": ""
}

###
POST http://localhost:3004/login/
Content-Type: application/json

{
    "username": "rahul",
    "password": "rahul12"

}

###
GET http://localhost:3004/profile
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTYzNzc2Mzc5NH0.ybHEjE6WuGat7oY5OBEwWgsaTsTQiT6IbMG5qXX0Sw0

###
GET http://localhost:3004/allusers/
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTYzNzc2Mzc5NH0.ybHEjE6WuGat7oY5OBEwWgsaTsTQiT6IbMG5qXX0Sw0

###
DELETE http://localhost:3004/remove/
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTYzNzc2Mzc5NH0.ybHEjE6WuGat7oY5OBEwWgsaTsTQiT6IbMG5qXX0Sw0

